changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]
      - github-actions[bot]

  categories:
    - title: 🔥 Cambios que rompen
      labels:
        - breaking-change
        - breaking

    - title: 🚀 Novedades
      labels:
        - feature
        - enhancement
        - feat

    - title: 🐛 Correcciones
      labels:
        - bug
        - fix
        - bugfix

    - title: ♿ Accesibilidad y contraste
      labels:
        - a11y
        - accessibility
        - contrast

    - title: 🎨 Tokens y escalas
      labels:
        - tokens
        - design-system

    - title: 📚 Documentación
      labels:
        - documentation
        - docs

    - title: 🧪 Pruebas
      labels:
        - test
        - testing

    - title: 🔧 Mantenimiento
      labels:
        - chore
        - refactor
        - maintenance

    - title: 🚀 CI/CD
      labels:
        - ci
        - github-actions
        - workflow

    - title: 📦 Dependencias
      labels:
        - dependencies
        - deps
