import { defineConfig } from 'tsup';

/**
 * `dist/tokens/theme.css` is NOT produced here: it is generated by
 * `scripts/build-tokens.mjs` after tsup, because `clean` wipes `dist/`.
 */
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'tokens/index': 'src/tokens/index.ts',
    'theme/index': 'src/theme/index.ts',
    'brand/index': 'src/brand/index.ts',
    'og/index': 'src/og/index.ts',
    'shiki/index': 'src/shiki/index.ts',
    'form/index': 'src/form/index.tsx',
    'chart/index': 'src/chart/index.tsx',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  treeshake: true,
  // No sourcemaps. They were 688 KB of a 1.1 MB tarball — `index.cjs.map` alone
  // weighed more than any brand PNG, and the PNGs are the product. Whoever needs
  // to debug the library has all of it in the repo, with its history.
  sourcemap: false,
  target: 'es2022',
  // The last two are OPTIONAL peer dependencies: only the project importing
  // `./form` or `./chart` installs them. They are here because in this repo they
  // are devDependencies — needed to compile and for the stories — and without
  // this line tsup would bundle them into what gets published.
  external: ['react', 'react-dom', 'react-hook-form', 'recharts'],
});
