/**
 * Generates the Tailwind output from `src/tokens/tokens.ts`.
 *
 * One source, generated outputs: `dist/tokens/theme.css` (`@theme`, for
 * projects on Tailwind v4). None of it is edited by hand and it is regenerated
 * on every build. Change a hex in `tokens.ts` and the output changes.
 *
 * If the v3 preset ever needs publishing again (an unmigrated portfolio), it is
 * one more emitter below reading the same `tokens`: the source does not change.
 *
 * It exports `themeCss` as well as writing it. `check-tokens-namespace.mjs` and
 * the regression test parse EXACTLY the CSS that gets published, rather than
 * restating the emission rules on their own: duplicating them is how the clash
 * between `--spacing-*` and Tailwind's `--container-*` scale slipped through.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { tokens } = await import(resolve(root, 'src/tokens/index.ts'));

const NOTICE = [
  '/*',
  ' * GENERATED by scripts/build-tokens.mjs from src/tokens/tokens.ts.',
  ' * Do not edit by hand: it is regenerated on every build.',
  ' *',
  ' * Usage in a Tailwind v4 project:',
  ' *   @import "tailwindcss";',
  ' *   @import "@eduardoalvarez/arrecife/tokens/theme.css";',
  ' *',
  ' * Dark is the primary mode and the default. A project in light mode',
  ' * declares data-theme="light" on <html>.',
  ' *',
  ' * Font families are declared by name: the project loads Bricolage',
  ' * Grotesque, Geist and JetBrains Mono however it prefers.',
  ' */',
].join('\n');

/** camelCase → kebab-case, for the custom property name. */
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const px = (n) => `${n}px`;

function colorsBlock(palette, indent = '  ') {
  return Object.entries(palette)
    .map(([name, hex]) => `${indent}--color-${kebab(name)}: ${hex};`)
    .join('\n');
}

function brandBlock(indent = '  ') {
  return Object.entries(tokens.brand)
    .map(([name, hex]) => `${indent}--color-brand-${kebab(name)}: ${hex};`)
    .join('\n');
}

function typographyBlock() {
  const lines = [];
  for (const [name, family] of Object.entries(tokens.fonts)) {
    lines.push(`  --font-${name}: ${family};`);
  }
  lines.push('');
  for (const [name, scale] of Object.entries(tokens.typeScale)) {
    lines.push(`  --text-${name}: ${px(scale.size)};`);
    if ('lineHeight' in scale) {
      lines.push(`  --text-${name}--line-height: ${scale.lineHeight};`);
    }
    if ('weight' in scale) {
      lines.push(`  --text-${name}--font-weight: ${scale.weight};`);
    }
    if ('tracking' in scale) {
      lines.push(`  --text-${name}--letter-spacing: ${scale.tracking};`);
    }
  }
  return lines.join('\n');
}

/**
 * `--color-series-1` … `--color-series-4`. Numbered rather than named, because a
 * series is not biolume: it is the first one in the chart, and the fact that
 * biolume happens to be its color today is a palette decision that can change
 * without touching the code that uses it.
 */
function seriesBlock(mode, indent = '  ') {
  return tokens.series[mode]
    .map((hex, i) => `${indent}--color-series-${i + 1}: ${hex};`)
    .join('\n');
}

function gradientsBlock(mode, indent = '  ') {
  return Object.entries(tokens.gradient[mode])
    .map(([name, value]) => `${indent}--gradient-${kebab(name)}: ${value};`)
    .join('\n');
}

function shapeBlock() {
  const lines = [];
  for (const [name, value] of Object.entries(tokens.radius)) {
    lines.push(`  --radius-${name}: ${px(value)};`);
  }
  lines.push('');
  // `stepMd` comes out as `--spacing-step-md` → `p-step-md`. The prefix exists
  // because xs/sm/md/lg/xl are the names of Tailwind's `--container-*` scale and
  // were swallowing it: see the comment in `tokens.ts`.
  for (const [name, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --spacing-${kebab(name)}: ${px(value)};`);
  }
  lines.push('');
  // Controls enter the spacing scale under their own prefix: they yield
  // px-control-md and size-control-icon, and are not offered as loose margins.
  for (const [name, value] of Object.entries(tokens.control)) {
    lines.push(`  --spacing-control-${kebab(name)}: ${px(value)};`);
  }
  lines.push('');
  // `nav` is a height (h-nav); `content` and `wide` are widths (max-w-content).
  //
  // They are listed one by one rather than looped, because the group is not
  // uniform: two of its members are `--spacing-*` and two are `--container-*`,
  // and a loop would have to guess which. The cost of that is real and it was
  // paid once — `navCompact` was added to `tokens.ts` and silently did not come
  // out here, so `h-nav-compact` resolved to nothing and the bar kept its 64.
  // Adding a size means adding its line.
  lines.push(`  --spacing-nav: ${px(tokens.size.nav)};`);
  lines.push(`  --spacing-nav-compact: ${px(tokens.size.navCompact)};`);
  lines.push(`  --spacing-sidebar: ${px(tokens.size.sidebar)};`);
  lines.push(`  --spacing-sidebar-rail: ${px(tokens.size.sidebarRail)};`);
  lines.push(`  --container-content: ${px(tokens.size.content)};`);
  lines.push(`  --container-wide: ${px(tokens.size.wide)};`);
  lines.push(`  --container-measure: ${tokens.limits.measure};`);
  lines.push('');
  lines.push(`  --shadow-standard: ${tokens.shadow.standard};`);
  lines.push('');
  lines.push(`  --duration-standard: ${tokens.motion.duration};`);
  lines.push(`  --ease-standard: ${tokens.motion.easing};`);
  return lines.join('\n');
}

export const themeCss = `${NOTICE}

/* The mode is chosen with data-theme. Dark is primary, so it is the default:
   a light project declares data-theme="light" on <html>. */
@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));
@custom-variant light (&:where([data-theme="light"], [data-theme="light"] *));

/* STATIC, and that word is the whole of a bug fix. Tailwind v4 emits a theme
   variable only if some utility it generated uses it, and a token read with
   var() from JS is asked for by no utility at all: seriesColor(i) returns
   var(--color-series-N) on purpose, so the color follows the mode instead of
   freezing to whichever one was live when the chart mounted. No project writes
   bg-series-1, so Tailwind dropped all four as unused, the var() resolved to
   nothing, and a fill that resolves to nothing is black — on a dark page,
   indistinguishable from «no data». No error in the console and none in the
   build; the report that arrived was «the information is not showing».

   With static, every token this file declares reaches :root whether a class
   asks for it or not, which is what a published token set is: a contract, not
   a subset of itself discovered by usage. It costs CSS — measured at +1.6 KB
   raw / +234 B gzipped for a project using the library's whole vocabulary, and
   +3.2 KB / +579 B for one that writes almost nothing — and it buys the
   removal of a whole class of silent failure rather than of one instance.
   See docs/decisions/ § 61. */
@theme static {
  /* --- color · dark mode (default) ------------------------------------- */
${colorsBlock(tokens.colors.dark)}

  /* --- brand · identical in both modes ----------------------------------- */
${brandBlock()}

  /* --- chart series · dark mode (default) -------------------------------- */
${seriesBlock('dark')}

  /* --- typography --------------------------------------------------------- */
${typographyBlock()}

  /* --- shape and rhythm --------------------------------------------------- */
${shapeBlock()}

  /* --- gradients · dark mode (default) ----------------------------------- */
${gradientsBlock('dark')}
}

/* --- color per mode, nestable ----------------------------------------------
   Both modes are emitted as their own blocks, not just light. That way a subtree
   can declare the opposite mode to the page and everything inside honours it:
   which is what a code block needs, since it sits on hull in both themes and
   therefore always carries light ink on top. */
[data-theme='dark'] {
${colorsBlock(tokens.colors.dark)}

${seriesBlock('dark')}

${gradientsBlock('dark')}
}

[data-theme='light'] {
${colorsBlock(tokens.colors.light)}

${seriesBlock('light')}

${gradientsBlock('light')}
}

/* --- the system's two gradients, as utilities -------------------------------
   They are the only two blocks with a gradient: the hero and the section panel.
   Making them utilities rather than arbitrary classes is what stops each project
   from writing its own angle. They follow the mode because they read the custom
   property. */
@utility gradient-hero {
  background-image: var(--gradient-hero);
}
@utility gradient-section {
  background-image: var(--gradient-section);
}

/* --- the third motion exception: the skeleton shimmer -----------------------
   The system does not animate, and this is the third exception, alongside the
   button spinner and the side panel. All of them are feedback about PROGRESS,
   not about state: a block that is still and a block that will never load look
   identical.

   1.4s linear, from the document. It sits behind motion-safe in the component. */
@keyframes arrecife-shimmer {
  from { background-position: 200% 0; }
  to { background-position: -200% 0; }
}

@utility shimmer {
  background-image: linear-gradient(
    90deg,
    transparent 0%,
    var(--color-hairline-hover) 50%,
    transparent 100%
  );
  background-size: 200% 100%;
  animation: arrecife-shimmer 1.4s linear infinite;
}

/* --- the fifth exception: the halo the CLI signature ends in ----------------
   The mark stays solid and RADIATES: a ring grows out of it to 5px and fades.
   It never turns off, and nothing about it is on-or-off.

   THIS IS WHAT THE CLI SIGNATURE ENDS IN. Both sites that draw that signature
   had it — cursos in app/globals.css, eduardoalvarez.dev in base.css — under
   the name cursor-ping, and the blog's copy sat there with nothing rendering
   it, because adopting the library's Footer had replaced its mark with a blink.
   The library had overruled the identity in the one direction it is not allowed
   to: it invented.

   That blink shipped in 0.6.0 as a caret utility and it is GONE. It was kept
   for one release on the grounds that a terminal caret is a real thing to want,
   which is true and is not a reason: nothing in the library drew it, no
   consumer had ever asked for it, and the argument that justified it had been
   written from first principles about terminals rather than read off the two
   sites that already had a signature. A utility with no consumer and no origin
   is not a feature, it is the invention still sitting there under a new label.
   See docs/decisions/ § 45.

   Its reason is the one the other four exceptions share: it is feedback about
   PROGRESS. A prompt that radiates says the terminal is live, which is the same
   thing the button spinner says and the same thing a still mark cannot say.
   With the caret gone the criterion is ONE again — progress or spatial
   continuity — and the legibility half § 23 opened turns out to have had
   exactly one member for its whole life.

   The color comes from --color-accent and not from a hex, so it follows the
   mode. cursos wrote it against its own --primary, which freezes to whichever
   mode was active; the blog hardcoded rgba(53, 214, 192, 0.7), which is this
   accent at 70 % and goes stale the day the accent moves. 1.5s ease-in-out,
   which is the cadence both arrived at.

   Behind motion-safe at the call site — the half NOT copied from cursos, whose
   span animates regardless. The blog guarded it, every other exception here is
   guarded, and at rest the bar is simply solid.
   See docs/decisions/ § 45. */
@keyframes arrecife-pulse {
  0%, 100% {
    box-shadow: 0 0 0 0 color-mix(in oklab, var(--color-accent) 70%, transparent);
  }
  50% {
    box-shadow: 0 0 0 5px transparent;
  }
}

@utility pulse-accent {
  animation: arrecife-pulse 1.5s ease-in-out infinite;
}

/* --- the accordion exception -----------------------------------------------
   The fourth one and, like the other three, it is not «it looks better»: a
   disclosure that reveals content with no transition makes everything below it
   JUMP, and whoever just clicked loses their place on the page. It is the same
   category as the side panel — a panel entering from an edge slides by
   definition — and not an entrance animation, which is what the system rejects:
   nothing new appears on screen here, a gap opens.

   Radix publishes the height as --radix-accordion-content-height. It lasts as
   long as everything else and uses the same curve, so it introduces no new
   timing. In the component it sits behind motion-safe. */
@keyframes arrecife-expand {
  from { height: 0; }
  to { height: var(--radix-accordion-content-height); }
}
@keyframes arrecife-collapse {
  from { height: var(--radix-accordion-content-height); }
  to { height: 0; }
}

@utility expand {
  animation: arrecife-expand var(--duration-standard) var(--ease-standard);
}
@utility collapse {
  animation: arrecife-collapse var(--duration-standard) var(--ease-standard);
}

/* --- the side panel exception ----------------------------------------------
   A panel entering from an edge slides by definition: held still it would be an
   off-centre modal. It is the second exception to "no displacement", and it was
   approved knowingly.

   It lasts as long as everything else and uses the same curve, so it introduces
   no new timing. In the component it sits behind motion-safe. */
@keyframes arrecife-slide-in-right { from { translate: 100% 0; } }
@keyframes arrecife-slide-out-right { to { translate: 100% 0; } }
@keyframes arrecife-slide-in-left { from { translate: -100% 0; } }
@keyframes arrecife-slide-out-left { to { translate: -100% 0; } }
@keyframes arrecife-slide-in-top { from { translate: 0 -100%; } }
@keyframes arrecife-slide-out-top { to { translate: 0 -100%; } }
@keyframes arrecife-slide-in-bottom { from { translate: 0 100%; } }
@keyframes arrecife-slide-out-bottom { to { translate: 0 100%; } }

@utility slide-in-right {
  animation: arrecife-slide-in-right var(--duration-standard) var(--ease-standard);
}
@utility slide-out-right {
  animation: arrecife-slide-out-right var(--duration-standard) var(--ease-standard);
}
@utility slide-in-left {
  animation: arrecife-slide-in-left var(--duration-standard) var(--ease-standard);
}
@utility slide-out-left {
  animation: arrecife-slide-out-left var(--duration-standard) var(--ease-standard);
}
@utility slide-in-top {
  animation: arrecife-slide-in-top var(--duration-standard) var(--ease-standard);
}
@utility slide-out-top {
  animation: arrecife-slide-out-top var(--duration-standard) var(--ease-standard);
}
@utility slide-in-bottom {
  animation: arrecife-slide-in-bottom var(--duration-standard) var(--ease-standard);
}
@utility slide-out-bottom {
  animation: arrecife-slide-out-bottom var(--duration-standard) var(--ease-standard);
}

/* --- the focus ring ---------------------------------------------------------
   The document gives it once, on the primary button: «focus ring 2px #35D6C0 +
   offset 3px». The code had it as three classes copied to twenty-nine call
   sites in twenty-four files, all of them at offset 2, and three audits in a row
   said so — the value was never argued down to 2, it was copied from the first
   component and inherited by the next twenty-eight.

   It is one utility for the reason § 15 gives: a list kept in sync by hand with
   another list ends up out of sync. Twenty-nine copies is twenty-nine chances to
   write the next one at offset 2 again, and nothing was checking.

   focus-ring-warm exists for the ONE control the ring cannot be biolume on:
   the conversion button is the system's only sand fill, and a biolume ring
   around it puts both of the brand's accents in the same three pixels. It sets
   only the color, so the width and the offset stay in one place.

   focus-ring-inset flips the OFFSET, and only the offset, for the same reason
   and by the same rule: an element that is focusable but sits inside a clipped
   container cannot wear a ring drawn 3px outside itself, because the container
   paints it away. CodeBlock is the case — its root carries overflow-hidden so
   its rounded corners hold, and its pre scrolls, so the pre has to be focusable.
   With the outward ring, three of its four sides were clipped and what was left
   read as a stray line under the header: a focus indicator that is present in
   the CSS and invisible on screen, which is WCAG 2.4.7 failing while looking
   fixed.

   It is -3px and not 0: at 0 the ring sits exactly on the border box and reads
   as a change of border rather than as a ring. The padding it eats into is
   p-step-md, so it never touches the text. Reach for it ONLY when a clipping
   ancestor is the reason — not because the outward ring looks too loud. */
@utility focus-ring {
  &:focus-visible {
    outline: 2px solid var(--color-accent);
    outline-offset: 3px;
  }
}
@utility focus-ring-warm {
  &:focus-visible {
    outline-color: var(--color-warm);
  }
}
@utility focus-ring-inset {
  &:focus-visible {
    outline-offset: -3px;
  }
}

/* The system's only transition, as a utility. States are communicated with
   border and color, not with movement: this class cannot animate anything else. */
@utility transition-standard {
  transition-property: ${tokens.motion.properties};
  transition-duration: var(--duration-standard);
  transition-timing-function: var(--ease-standard);
}
`;

// It only writes when run as a script. Imported, it is a source of CSS.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = resolve(root, 'dist/tokens/theme.css');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, themeCss, 'utf8');

  console.log(`arrecife · tokens → ${target.replace(`${root}/`, '')}`);
}
